### ISSUE TITLE
Name - this thing needs a name

### ISSUE THREAD

**Issue by betatim** [betatim/openscienceprize#13]
What to call this project?

**Comment by cranmer** [comment]
http://satyrn.org

**Comment by betatim** [comment]
Via [twitter](https://twitter.com/ctitusbrown/status/702545137314897920): plut0, neptoon, marz, irth, vinus

**Comment by m3gan0** [comment]
"satyrn" and "vinus" allow you to reference layers of information - i.e. rings of related information held together by a central work.
Metaphors, man.

**Comment by betatim** [comment]
We need a name for the team **and** for the project. Twice as much creativity needed!

**Comment by cranmer** [comment]
https://answers.yahoo.com/question/index?qid=20111130193528AASscD8
Satyrnians? :grimacing: 

Why do we need a name for the team? Jupyter, Project Jupyter, Jupyter team
Why not just Satyrn Team ? (if we choose that name)

**Comment by betatim** [comment]
The team needs a name because the submission form requires one :-p

I need to warm up to satyrn, sounds too much like satire (somehow I got
that association going in my head and can't unhear it again) :-/

**Comment by tritemio** [comment]
@betatim to me too. To me satyrn sounds like satyr.

**Comment by anaderi** [comment]
My 2c: 
like 'youtube' (everyone as a broadcasting company) we can name our project 'youscience' or 'yousci'

**Comment by rougier** [comment]
R³ (Reusable - Reproducible - Replicable)

**Comment by anaderi** [comment]
One more 'r' for 'research'? )

**Comment by betatim** [comment]
I like it!

rcubed (spelt out like this)?

rrroar? (fine tune the number of leading R)

`RR - reusable research` or `R^2 - reusable research`, `rr` would also make for a nice short command line program name.

**Comment by rougier** [comment]
R³ - Reusable & Reproducible Research ?

**Comment by betatim** [comment]
:rocket:
