### ISSUE TITLE
Budget

### ISSUE THREAD

**Issue by cranmer** [betatim/openscienceprize#26]
It wasn't clear from my brief look at https://www.openscienceprize.org/res/p/FAQ/ what is required in terms of budgeting.

**Comment by betatim** [comment]
As I understand it it is a prize. So if you win they send you a cheque and
you spend the money.

**Comment by cranmer** [comment]
Ok, but that doesn't mean that we don't need to say what we will do with the money and justify it. All I see is `How will the phase I competition be judged?
All applications will be evaluated by the staff from the partner funders– to ensure that they are within scope and budget and fulfil the prize criteria.`

Also, we should probably have some idea of what we would do with it (specifically) even if they don't require it.

**Comment by betatim** [comment]
The project should be run like an open-source project: anyone can join and become a contributor to the software, documentation and specs we create. Building a community around these projects should be a focus. We should cover out of pocket expenses to achieve that goal. Travel to/fees for a workshop/sprint/community event to build contacts and recruit new contributors. We should be organising our own event to build consensus on the spec file etc.

Hosting for a demonstrator and other cloud services that we might need. However we should try and get those sponsored by AWS, rackspace, etc. I would veto buying actual physical objects as it isn't clear what should happen with them at the end of the project.

I am able to commit a significant amount of my time (averaging several days per week) to this project in the next six months. I will want to charge the project for that time.

**Comment by cranmer** [comment]
That sounds totally reasonable, and much stronger than “send check, spend money” :-)

**Comment by betatim** [comment]
1. Receive cheque
2. buy :tada: :balloon: :cake: :confetti_ball:
3. ...
4. deliver prototype

**Comment by ctb** [comment]
I think this is resolved in the proposals.
