### ISSUE TITLE
Second round of thorough comments

### ISSUE THREAD

**Issue by betatim** [betatim/openscienceprize#33]
Hello,

this is a proposal for http://openscienceprize.org. We propose to build tools to make reusability and composition a first-class citizen in computer aided research. Enabling the publication of dynamic and interactive scientific narratives that can be verified, altered, reused, and cited.

Comments and feedback welcome! Right now the focus should be on the structure of the proposal. What is unclear, missing, or superfluous. Language and spelling second.

To gather feedback directly on the document it would be ideal if you could use [hypothes.is](http://hypothes.is) via this link: https://via.hypothes.is/https://github.com/betatim/openscienceprize/blob/7cd9fd5615b44daf9e720cdc486a4f9ec8054979/proposal.md. (simply highlight the text you want to comment on, there should be a toolbar on the right edge of your browser window, if too much hassle see next point) Next best is to leave a comment on [this issue](https://github.com/betatim/openscienceprize/issues/33) or email Tim betatim@gmail.com.

Thanks, I owe all of you a drink of your choice,
T

**Comment by khinsen** [comment]
In addition to my annotations, I have a general comment. The Open Science Prize emphasizes health research and the life sciences. There is nothing addressing this in the current proposal. I am not volunteering to write this as I am on the fringe of life sciences myself. Maybe @ctb could look at this?

**Comment by betatim** [comment]
:+1: My best effort is the nod to meta analysis and that we should try and find a similar example to the LEP data one based in life sciences/biology. Maybe the human genome project and related analysis? But like you I'm an outsider to that field.

**Comment by cranmer** [comment]
Hi, trying to contribute here, but a little confused about if we are using hypothesis or GitHub as primary way of editing the doc.

**Comment by betatim** [comment]
Ideally now comment on changes proposed in #35

**Comment by betatim** [comment]
Not sure what the best way is of getting to a state where comments/changes will be proposed by individuals as a PR (which is the way to do this really ...)

**Comment by khinsen** [comment]
I don't think there is a good way. Prose is not code. An Etherpad would probably be a better medium for interactive editing.

**Comment by ctb** [comment]
Google Docs with commenting work pretty well, and it's closer to the format we have to actually submit. @betatim what do you think about transferring it over there?

**Comment by betatim** [comment]
For live simultaneous editing google docs is pretty good. For async I think PRs are the way to go (once you have a base on top of which you can make small-ish PRs). You almost always want to discuss edits before applying them, which is why I think PRs is the way to go unless you are on the phone/chat with each other editing away.

For submission I was just going to run `pandoc` on the markdown which produces a PDF (via latex).

**Comment by ctb** [comment]
On Sun, Feb 28, 2016 at 07:19:56AM -0800, Tim Head wrote:
> For live simultaneous editing google docs is pretty good. For async I think PRs are the way to go (once you have a base on top of which you can make small-ish PRs). You almost always want to discuss edits before applying them, which is why I think PRs is the way to go unless you are on the phone/chat with each other editing away.
> 
> For submission I was just going to run `pandoc` on the markdown which produces a PDF (via latex).

OK - sounds good.  I will continue in the PR vein, and work on #42 next.
