### ISSUE TITLE
Renaming

### ISSUE THREAD

**Issue by betatim** [betatim/openscienceprize#45]
@ctb suggested "everpub" as a name. Thoughts?

I like it, not only because it builds on the theme of everware.

**Comment by rougier** [comment]
:+1:  (only 31,000 results on google, might easy enough to google it later)

**Comment by betatim** [comment]
The everpub, where we serve free :beer: with every :notebook:

**Comment by glouppe** [comment]
+1, rrr is not a good name (not obvious how to pronounce it, hard to google, etc)

**Comment by anaderi** [comment]
Or you buy 🍻 To authors of publications you like... Probably 'fork ' should be renamed accordingly)) anyway I like the idea.
