### ISSUE TITLE
Check list (kind of)

### ISSUE THREAD

**Issue by rougier** [betatim/openscienceprize#75]
To be done:
* [ ] Abstract to be written (= executive summary for submission, 300 words max)  
* [ ] `team.md` to be completed (see #47)
* [ ] Build the final PDF and review errors / glitches

There are trailing comments in the proposal, I've listed them here just to be sure to not forget to process them before actual submission:
* [ ] "many others (XXX more here)" to be completed or removed
* [ ] "remote containers; (XXX more here)." to be completed or removed
* [ ] "be addressed. (refs)" to be completed or removed
* [ ] "this proposal (XXX)" to be removed ?
* [ ] "and N people"  N = 5 ?
* [ ] "place holder XXX" maybe it's time to remove it ?

**Comment by betatim** [comment]
I added this to #46 and track it there if that is Ok with you?

**Comment by rougier** [comment]
sure.

**Comment by betatim** [comment]
Cool.
