### ISSUE TITLE
Nicer PDF

### ISSUE THREAD

**Issue by rougier** [betatim/openscienceprize#89]
Too many PRs on the queue and I've to go:

For a nicer PDF output (for title and authors):

`Makefile`:
```
FORMAT   = markdown+mmd_title_block
pdf: proposal.md
        pandoc --standalone --from $(FORMAT) -V colorlinks proposal.md -o proposal.pdf
```

`Proposal.md`:
```
Title:  Everpub: reusable research, 21st century style
Author: Tim Head (Europe lead), Titus Brown (US lead)

## Introduction
...
```

**Comment by betatim** [comment]
I can take care of this once we get the other PRs sorted. Thanks for
knowing or looking up how to do this!
